# Generated by Django 2.2.2 on 2019-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegweight', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
